### PR TITLE
l10n: Triple dot to ellipsis

### PR DESCRIPTION
**Pull request by rakekniven**
Reported at Transifex.

Signed-off-by: rakekniven <mark.ziegler@rakekniven.de>

### CODE REVIEW

**Comment by rakekniven** [comment]
Hello @nerzhul ,

is your app still maintained and working with e. g. Nextcloud 18?

Cheers

**Comment by e-alfred** [comment]
The Nextcloud app itself is, but @nerzhul needs to make a release to the App Store for both OCSMS and the Weather app. Sadly only he can push new releases to the App Store.

**Comment by nerzhul** [comment]
hello, this app is not published anymore on the play store and has been evicted for obscure bot reason on the play store

**Comment by rakekniven** [comment]
> hello, this app is not published anymore on the play store and has been evicted for obscure bot reason on the play store

Does this mean that the app not installed and used anymore?

I was confused about the wording App Store. Is it Nextcloud App Store? Or Google App Store?

**Comment by e-alfred** [comment]
For the Android app (this repository) it is F-Droid for now as long as we can't get back into the Play Store. For OCSMS (the Nextcloud companion app to the Android app) it is the Nextcloud App Store. Both apps (client and server side) are needed to make SMS sync work.

@nerzhul Can you make a release of the Nextcloud apps to the Nextcloud App Store?

**Comment by rakekniven** [comment]
Can the be merged please?

**Pull request merged**
